<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inner.Monitoring.Application\Inner.Monitoring.Application.csproj" />
    <ProjectReference Include="..\Inner.Monitoring.Infrastructure.Sqlite\Inner.Monitoring.Infrastructure.Sqlite.csproj" />
  </ItemGroup>

</Project>
