server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # O fallback pro index.html é essencial para o React Router (ex: recarregar na rota /app não dar 404 Not Found)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configurações de caching para arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff|ttf)$ {
        expires max;
        log_not_found off;
    }
}
